CREATE DATABASE congomoney;

USE congomoney;

CREATE TABLE client
(
	UID        VARCHAR(30),
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME  VARCHAR(30) NOT NULL,
    GENDER     VARCHAR(10) NOT NULL,
    DOB DATE NOT NULL,
    PHONE      VARCHAR(13) NOT NULL,
    ADDRESS    VARCHAR(255),
    CREATED_AT TIMESTAMP,
    
    PRIMARY KEY (UID)
) ENGINE = InnoDB;

CREATE TABLE account
(
	ID_ACC   VARCHAR(30),
    DATE_ACC TIMESTAMP,
    BALANCE FLOAT(255,2) DEFAULT '0.00',
   
    PRIMARY KEY (ID_ACC)
) ENGINE = InnoDB;

CREATE TABLE depot
(
	ID_DEP     INT,
    UID_DEP_CL VARCHAR(30) NOT NULL,
    ID_DEP_ACC VARCHAR(30) NOT NULL,
    DATE_DEP   TIMESTAMP,
    AMOUNT_DEP FLOAT(255,2),
    
    PRIMARY KEY (ID_DEP),
    FOREIGN KEY FK_DEP_CL (UID_DEP_CL) 
    REFERENCES client (UID) 
    ON UPDATE CASCADE,
 	FOREIGN KEY FK_DEP_ACC (ID_DEP_ACC) 
    REFERENCES account (ID_ACC) 
    ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE retrait
(
	ID_RET INT,
    UID_RET_CL VARCHAR(30) NOT NULL,
    ID_RET_ACC VARCHAR(30) NOT NULL,
    DATE_RET TIMESTAMP,
    AMOUNT_RET FLOAT(255,2),
    
    PRIMARY KEY (ID_RET),
    FOREIGN KEY FK_RET_CL (UID_RET_CL) 
    REFERENCES client (UID) 
    ON UPDATE CASCADE,
 	FOREIGN KEY FK_RET_ACC (ID_RET_ACC) 
    REFERENCES account (ID_ACC) 
    ON UPDATE CASCADE
) ENGINE = InnoDB;